// packages/client/web/src/app/main.jsx
import React from 'react';
import { createBatchingNetworkInterface } from 'apollo-client';
import { addApolloLogging } from 'apollo-logger';
import { ApolloProvider } from 'react-apollo';
import createHistory from 'history/createBrowserHistory';
import { ConnectedRouter, routerMiddleware } from 'react-router-redux';
import { addPersistedQueries } from 'persistgraphql';
import { SubscriptionClient } from 'subscriptions-transport-ws';
// eslint-disable-next-line import/no-unresolved, import/no-extraneous-dependencies, import/extensions
import queryMap from 'persisted_queries.json';
import ReactGA from 'react-ga';

import createApolloClient from '../../../../common/apollo_client';
import createReduxStore from '../../../../common/redux_store';
import routes from './routes';
import { app as settings } from '../../app.json';

import '../styles/styles.scss';

let networkInterface;
if (__CLIENT__) {
  networkInterface = new SubscriptionClient((__BACKEND_URL__ || (window.location.origin + '/graphql'))
    .replace(/^http/, 'ws')
    .replace(/:[0-9]+/, ':' + settings.apiPort), {
      reconnect: true
  });
} else {
  networkInterface = createBatchingNetworkInterface({
    opts: {
      credentials: "same-origin",
    },
    batchInterval: 20,
    uri: __BACKEND_URL__ || "/graphql",
  });
}

if (__PERSIST_GQL__) {
  networkInterface = addPersistedQueries(networkInterface, queryMap);
}

if (settings.apolloLogging) {
  networkInterface = addApolloLogging(networkInterface);
}

const client = createApolloClient(networkInterface);

let initialState = {};

if (window.__APOLLO_STATE__) {
  initialState = window.__APOLLO_STATE__;
}

const history = createHistory();

// Initialize Google Analytics and send events on each location change 
ReactGA.initialize('UA-000000-01'); // Replace your Google tracking code here

history.listen((location) => {
  ReactGA.set({ page: location.pathname });
  ReactGA.pageview(location.pathname);
});

const store = createReduxStore(initialState, client, routerMiddleware(history));

if (module.hot) {
  module.hot.dispose(() => {
    // Force Apollo to fetch the latest data from the server
    delete window.__APOLLO_STATE__;
  });
}

const Main = () => (
  <ApolloProvider store={store} client={client}>
    <ConnectedRouter history={history}>
      {routes}
    </ConnectedRouter>
  </ApolloProvider>
);

export default Main;

// packages/client/src/app/Main.tsx
import { Component } from '@angular/core';
import React from 'react';
import { ApolloProvider } from 'react-apollo';
import { Provider } from 'react-redux';
import createHistory from 'history/createBrowserHistory';
import { ConnectedRouter, routerMiddleware } from 'react-router-redux';
import ReactGA from 'react-ga';

import RedBox from './RedBox';
import createApolloClient from '../../../common/createApolloClient';
import createReduxStore, { storeReducer } from '../../../common/createReduxStore';
import Routes from './Routes';
import modules from '../modules';
import log from '../../../common/log';
import { apiUrl } from '../net';
import settings from '../../../../settings';

log.info(`Connecting to GraphQL backend at: ${apiUrl}`);

const client = createApolloClient({
  apiUrl,
  createNetLink: modules.createNetLink,
  links: modules.link,
  connectionParams: modules.connectionParams,
  clientResolvers: modules.resolvers
});
const history = createHistory();
const logPageView = (location: any) => {
  ReactGA.set({ page: location.pathname });
  ReactGA.pageview(location.pathname);
};
let store: any;

// Initialize Google Analytics and send events on each location change
ReactGA.initialize(settings.analytics.ga.trackingId);
logPageView(window.location);

history.listen(location => logPageView(location));

if (module.hot && module.hot.data && module.hot.data.store) {
  store = module.hot.data.store;
  store.replaceReducer(storeReducer);
} else {
  store = createReduxStore({}, client, routerMiddleware(history));
}

if (module.hot) {
  module.hot.dispose(data => {
    data.store = store;
    delete window.__APOLLO_STATE__;
  });
}

class ServerError extends Error {
  constructor(error: any) {
    super();
    for (const key of Object.getOwnPropertyNames(error)) {
      this[key] = error[key];
    }
    this.name = 'ServerError';
  }
}

interface MainState {
  error?: ServerError;
  info?: any;
  ready?: boolean;
}

class Main extends React.Component<any, MainState> {
  constructor(props: any) {
    super(props);
    const serverError = window.__SERVER_ERROR__;
    serverError ? (this.state = { error: new ServerError(serverError), ready: true }) : (this.state = {});
  }

  public componentDidCatch(error: ServerError, info: any) {
    this.setState({ error, info });
  }

  public render() {
    return this.state.error ? (
      <RedBox error={this.state.error} />
    ) : (
      modules.getWrappedRoot(
        <Provider store={store}>
          <ApolloProvider client={client}>
            {modules.getDataRoot(<ConnectedRouter history={history}>{Routes}</ConnectedRouter>)}
          </ApolloProvider>
        </Provider>
      )
    );
  }
}

@Component({
  selector: 'body div:first-child',
  template: '<h1>Hello, {{name}}</h1>'
})
class MainComponent {
  public name = 'Angular';
}

export { client, MainComponent };
