// modules/look/client-react/ui-antd/components/PageLayout.jsx
import React from 'react';
import PropTypes from 'prop-types';
import { Layout } from 'antd';

import settings from '@gqlapp/settings-common';

import NavBar from './NavBar';

const { Header, Content, Footer } = Layout;

class PageLayout extends React.Component {
  render() {
    const { children, navBar } = this.props;

    return (
      <Layout>
        {navBar !== false && (
          <Header className="no-print">
            <NavBar />
          </Header>
        )}
        <Content id="content" style={{ background: '#fff', padding: 24 }}>
          {children}
        </Content>
        <Footer className="no-print" style={{ textAlign: 'center' }}>
          &copy; {new Date().getFullYear()}. {settings.app.name}.
        </Footer>
      </Layout>
    );
  }
}

PageLayout.propTypes = {
  children: PropTypes.node,
  navBar: PropTypes.bool
};

export default PageLayout;

// modules/look/client-vue/ui-bootstrap/components/PageLayout.vue
<template>
  <article class='d-flex flex-column flex-grow-1'>
    <section class='d-flex flex-column flex-grow-1 flex-shrink-0'>
      <header class='d-flex flex-column'>

      </header>
      <b-container id='content'>
        <slot></slot>
      </b-container>
    </section>
    <footer class='d-flex flex-shrink-0 justify-content-center'>
      <span>&copy; {{ now }}</span>
    </footer>
  </article>
</template>

<script lang="ts">
import settings from '@gqlapp/settings-common';

import Footer from './Footer.vue';

export default {
  name: 'PageLayout',
  components: {
    Footer,
  },
  computed: {
    now() {
      return `${new Date().getFullYear()}. ${settings.app.name}.`;
    }
  },
};
</script>
