// modules/counter/client-angular/clientCounter/index.ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { resolvers } from '@module/counter-common';
import CounterModule from '../CounterModule';
import { ClientCounterButtonComponent, ClientCounterViewComponent } from './components/ClientCounterView';

@NgModule({
  imports: [CommonModule],
  declarations: [ClientCounterButtonComponent, ClientCounterViewComponent],
  exports: [ClientCounterButtonComponent, ClientCounterViewComponent]
})
class ClientCounterModule {}

export default new CounterModule({
  resolver: [resolvers],
  counterModule: [ClientCounterModule]
});

// modules/counter/client-react/clientCounter/index.tsx
import React from 'react';

import resources from './locales';
import ClientCounter from './containers/ClientCounter';
import CounterModule from '../CounterModule';
import { resolvers } from '@module/counter-common';

export default new CounterModule({
  resolver: [resolvers],
  localization: [{ ns: 'clientCounter', resources }],
  counterComponent: [<ClientCounter />]
});
