// modules/counter/client-vue/containers/Counter.vue
<template>
  <page-layout>
    <div v-for='counter in counters' :key=counter.name>
      <component v-bind:is=counter></component>
    </div>
  </page-layout>
</template>

<script>
import Vue from 'vue';
import counters from '../counters';
import { PageLayout } from '@gqlapp/look-client-vue';

export default {
  name: 'CounterContainer',
  components: {
    PageLayout,
  },
  data: () => ({
    counters: counters.counterComponent.map(component => component)
  }),
};
</script>

// modules/counter/client-react/containers/Counter.tsx
import React from 'react';
import Helmet from 'react-helmet';

import { PageLayout } from '@gqlapp/look-client-react';
import settings from '../../../../settings';
import { translate, TranslateFunction } from '@gqlapp/i18n-client-react';
import counters from '../counters';

interface CounterProps {
  t: TranslateFunction;
}

const Counter = ({ t }: CounterProps) => (
  <PageLayout>
    <Helmet
      title={`${settings.app.name} - ${t('title')}`}
      meta={[
        {
          name: 'description',
          content: `${settings.app.name} - ${t('meta')}`
        }
      ]}
    />
    {counters.counterComponent.map((component: any, idx: number, items: any) =>
      React.cloneElement(component, { key: idx + items.length })
    )}
  </PageLayout>
);

export default translate('counter')(Counter);
